### PR TITLE
Add proxy support to GrapheneWebsocketRPC.

### PR DESCRIPTION
**Pull request by jhtitor**
Note: for this to work properly, websocket needs to be extended with pysocks support, as done here [1]

[1]: https://github.com/jhtitor/websocket-client

:(

### CODE REVIEW

**Comment by xeroc** [comment]
Before merging this, do you think we should bump a certain verison of websocket-client into setup.py?

**Comment by jhtitor** [comment]
Well, the situation is as follows:
- Official websocket-client has built-in HTTP proxies. Those will work.
- My fork of websocket-client adds support for SOCKS proxies.
- It appears websocket-client is unmaintained, my [PR] went without notice.

 [PR]: https://github.com/websocket-client/websocket-client/pull/417

Ideally, upstream would merge the fork, and we just bump the minimal version.
More practically (given their silence), would probably be to maintain our own version of this library.

**Comment by xeroc** [comment]
I have refactored the API stuff to make it more clear that we can talk websockets and HTTP requests.
Maybe worth another refactoring to add a websockets.socks sub class?

**Comment by jhtitor** [comment]
Good news! Upstream has merged the pysocks patch, so there is no need to maintain our own version of websocket-client library after all. Both HTTP and SOCKS proxies should work out-of-the-box now.

I've refactored this PR to support both HTTP and Websocket RPCs (as per your new class hierarchy).

**Comment by xeroc** [comment]
Great!
Just in time for the 1.0 release :D

**Pull request merged**
